### PR TITLE
fix(channel_endpoint): extend mls for all sessions

### LINKED ISSUE #393: Add channel endpoint to all the session types
Add channel moderator to all the session types, in order to enable MLS on any kind of session.

### PR DESCRIPTION
**Pull request by msardara**
# Description

Right now MLS is implemented only for groups, while we want it also for unicast sessions.

Fixes #393 

## Type of Change

- [ ] Bugfix
- [x] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](/agntcy/repo-template/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [x] New code contribution is covered by automated tests
- [x] All new and existing tests pass

### CODE REVIEW

File: data-plane/core/service/src/app.rs [hunk 1]
```diff
@@ -875,46 +784,56 @@ where
...
+                            .await?
+                    }
+                    ProtoSessionType::SessionPubSub => {
+                        let mut conf = self.default_stream_conf.read().clone();
+                        conf.direction = SessionDirection::Bidirectional;
+                        conf.mls_enabled = message.message.contains_metadata(METADATA_MLS_ENABLED);
+                        self.create_session(SessionConfig::Streaming(conf), Some(id))
+                            .await?
+                    }
+                    _ => {
```
Comment (micpapal) [inline data-plane/core/service/src/app.rs:834]: here the streaming session is missing.

File: data-plane/core/service/src/fire_and_forget.rs [hunk 2]
```diff
@@ -560,27 +607,46 @@ where
...
+                    .map_err(|e| SessionError::SlimTransmission(e.to_string()))
             }
             ProtoSessionMessageType::FnfAck => {
                 // Remove the timer and drop the message
                 self.stop_and_remove_timer(message_id)
             }
-            ProtoSessionMessageType::FnfDiscovery => {
+            ProtoSessionMessageType::ChannelDiscoveryRequest => {
+                // Handle sticky session discovery
+                self.handle_channel_discovery_request(message).await
```
Comment (micpapal) [inline data-plane/core/service/src/fire_and_forget.rs]: this should be handle inside app before the creation of the session in handle_message_from_slim_without_session

File: data-plane/core/service/src/fire_and_forget.rs [hunk 3]
```diff
@@ -255,77 +295,80 @@ where
...
-            Some(SlimHeaderFlags::default().with_forward_to(message.message.get_incoming_conn())),
-            "sticky_session_discovery_reply",
-            vec![],
-        );
-
-        // Set the session header type to FnfDiscoveryReply
-        let session_header = sticky_session_reply.get_session_header_mut();
-        session_header.set_session_message_type(ProtoSessionMessageType::FnfDiscoveryReply);
-        session_header.set_session_type(ProtoSessionType::SessionFireForget);
+        // pass the message to the channel endpoint
```
Comment (micpapal) [inline data-plane/core/service/src/fire_and_forget.rs:343]: do we need these functions? handle_channel_join_request is the only function that updates the session state, the other two simple call channel_endpoint.on_message like at line 645

Comment (msardara) [reply data-plane/core/service/src/fire_and_forget.rs:343]: I kept the wrappers in case we need to add stuff. We can leave as it is for now, I will do another iteration soon in any case
